vim.o.relativenumber = false
vim.o.background = "light"
vim.o.spelllang = "ru_ru,en_us"
vim.o.linebreak = true
vim.o.showbreak = "↪| "
vim.o.swapfile = false
vim.wo.wrap = true
vim.g.autoformat = false
vim.o.smartindent = false
vim.api.nvim_set_hl(0, "@symbol", {link = "Identifier"})
